# Generated by Django 2.2.10 on 2020-03-06 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
