# Generated by Django 2.2.10 on 2020-03-08 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200308_0014'),
        ('users', '0003_delete_group'),
    ]

    operations = [
    ]
