# Generated by Django 2.2.10 on 2020-03-08 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20200308_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='current_users',
            new_name='current_user',
        ),
    ]
