# Generated by Django 2.2.10 on 2020-03-09 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200309_0045'),
        ('users', '0004_merge_20200308_2207'),
    ]

    operations = [
    ]
