# Generated by Django 2.2.10 on 2020-03-09 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LyncUp', '0004_auto_20200308_2204'),
        ('LyncUp', '0006_post_group'),
    ]

    operations = [
    ]
