# Generated by Django 2.2.10 on 2020-03-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LyncUp', '0007_merge_20200309_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(default='default_group.jpg', upload_to='group_pics'),
        ),
    ]
